import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rename, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';
import test from 'node:test';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const repositoryRoot = import.meta.dirname.endsWith(`${sep}dist${sep}test`)
  ? join(import.meta.dirname, '..', '..')
  : join(import.meta.dirname, '..');
const script = join(repositoryRoot, 'scripts', 'sync-agent-auto-workflow.mjs');

test('workflow sync is byte and mode stable and check rejects stale generated bytes', async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'workflow-import-'));
  const codexHome = join(root, 'codex-home');
  const repoRoot = join(root, 'repo');
  const outputRoot = join(root, 'output');
  const configPath = join(repoRoot, 'source.json');
  await mkdir(join(codexHome, 'skills', 'alpha', 'agents'), { recursive: true });
  await mkdir(join(codexHome, 'skills', 'alpha', 'references'), { recursive: true });
  await mkdir(join(codexHome, 'docs', 'agents'), { recursive: true });
  await mkdir(join(codexHome, 'agents'), { recursive: true });
  await mkdir(join(repoRoot, 'overlays', 'operations', 'alpha'), { recursive: true });
  await mkdir(join(repoRoot, 'overlays', 'schemas'), { recursive: true });
  await writeFile(join(codexHome, 'skills', 'alpha', 'SKILL.md'), '# Alpha\n\nRead [reference](references/r.md).\n');
  await writeFile(join(codexHome, 'skills', 'alpha', 'agents', 'openai.yaml'), 'interface:\n  display_name: Alpha\n');
  await writeFile(join(codexHome, 'skills', 'alpha', 'references', 'r.md'), 'See [policy](../../../docs/agents/policy.md).\n');
  await writeFile(join(codexHome, 'docs', 'agents', 'policy.md'), '# Policy\n');
  await writeFile(join(codexHome, 'agents', 'reviewer-fast.toml'), 'name = "reviewer_fast"\nsandbox_mode = "read-only"\n');
  await writeFile(join(repoRoot, 'overlays', 'operations', 'alpha', 'SKILL.md'), '# Alpha operation\n');
  await writeFile(join(repoRoot, 'overlays', 'schemas', 'alpha.json'), '{}\n');
  await writeFile(configPath, `${JSON.stringify({
    version: 1,
    personalSkills: ['alpha'],
    repositorySkills: [],
    sharedDocs: ['policy.md'],
    profiles: { reviewer_fast: 'reviewer-fast.toml' },
    overlayRoot: 'overlays',
    adaptations: [
      { id: 'resolved-codex-home', from: '<resolved-codex-home>', to: '$CODEX_ORCHESTRATOR_WORKFLOW_ROOT' },
      { id: 'default-codex-skills', from: '${CODEX_HOME:-$HOME/.codex}/skills', to: '../../skills' },
      { id: 'codex-home-skills', from: '$CODEX_HOME/skills', to: '../../skills' },
      { id: 'default-codex-docs', from: '${CODEX_HOME:-$HOME/.codex}/docs/agents/', to: '../../docs/agents/' },
      { id: 'codex-home-docs', from: '$CODEX_HOME/docs/agents/', to: '../../docs/agents/' },
    ],
    operations: {
      alpha: {
        entry: 'operations/alpha/SKILL.md', sourceSkill: 'alpha', outputSchema: 'schemas/alpha.json',
        profile: 'reviewer_fast',
        policy: {
          sandboxMode: 'read-only', cwdClass: 'worktree', worktreeAccess: 'read-only', writableRootClasses: [],
          runnerPostcondition: 'report-only', network: 'deny', networkHosts: [], mcpTools: [],
          approvalCeiling: 'never', externalWrite: false,
        },
      },
    },
  }, null, 2)}\n`);

  const args = ['sync', '--codex-home', codexHome, '--repo-root', repoRoot, '--config', configPath, '--output-root', outputRoot];
  await execFileAsync(process.execPath, [script, ...args]);
  const first = await digestTree(outputRoot);
  await execFileAsync(process.execPath, [script, ...args]);
  assert.deepEqual(await digestTree(outputRoot), first);
  await execFileAsync(process.execPath, [script, 'check', ...args.slice(1)]);

  await chmod(join(outputRoot, 'skills', 'alpha', 'SKILL.md'), 0o644);
  await writeFile(join(outputRoot, 'skills', 'alpha', 'SKILL.md'), '# stale\n');
  await assert.rejects(execFileAsync(process.execPath, [script, 'check', ...args.slice(1)]), /stale|mismatch/iu);
  await t.test('manifest binds the declared transitive closure', async () => {
    const manifest = JSON.parse(await readFile(join(outputRoot, 'manifest.json'), 'utf8')) as {
      generationHash: string;
      files: Array<{ path: string }>;
      skills: Record<string, { files: string[] }>;
    };
    assert.match(manifest.generationHash, /^[a-f0-9]{64}$/u);
    assert.deepEqual(manifest.skills.alpha.files, [
      'docs/agents/policy.md',
      'skills/alpha/SKILL.md',
      'skills/alpha/agents/openai.yaml',
      'skills/alpha/references/r.md',
    ]);
    assert.equal(manifest.files.some((file) => file.path === 'docs/agents/policy.md'), true);
  });
});

test('workflow source v2 binds dependency skills and keeps evals outside runtime operation closure', async () => {
  const root = await mkdtemp(join(tmpdir(), 'workflow-import-v2-'));
  const codexHome = join(root, 'codex-home');
  const repoRoot = join(root, 'repo');
  const outputRoot = join(root, 'output');
  const configPath = join(repoRoot, 'source.json');
  for (const skill of ['alpha', 'beta']) {
    await mkdir(join(codexHome, 'skills', skill, 'agents'), { recursive: true });
    await mkdir(join(codexHome, 'skills', skill, 'evals'), { recursive: true });
    await writeFile(join(codexHome, 'skills', skill, 'SKILL.md'), `# ${skill}\n`);
    await writeFile(join(codexHome, 'skills', skill, 'agents', 'openai.yaml'), `interface:\n  display_name: ${skill}\n`);
    await writeFile(join(codexHome, 'skills', skill, 'evals', 'evals.json'), `${JSON.stringify({
      schema_version: 1,
      skill,
      cases: [{ id: `${skill}-case`, prompt: `Use ${skill}.`, expected: [`used ${skill}`], forbidden: [`ignored ${skill}`] }],
    })}\n`);
  }
  await mkdir(join(codexHome, 'docs', 'agents'), { recursive: true });
  await mkdir(join(codexHome, 'agents'), { recursive: true });
  await mkdir(join(repoRoot, 'overlays', 'operations', 'alpha'), { recursive: true });
  await mkdir(join(repoRoot, 'overlays', 'schemas'), { recursive: true });
  await writeFile(join(codexHome, 'docs', 'agents', 'routing.md'), '# Routing\n\nSee [beta](../../skills/beta/SKILL.md).\n');
  await writeFile(join(codexHome, 'docs', 'agents', 'coding-skill-evals.json'), `${JSON.stringify({
    schema_version: 1,
    cases: [{ id: 'cross-case', prompt: 'Route work.', expected: ['routed'], forbidden: ['guessed'] }],
  })}\n`);
  await writeFile(join(codexHome, 'agents', 'reviewer-fast.toml'), 'name = "reviewer_fast"\nsandbox_mode = "read-only"\n');
  const operationPath = join(repoRoot, 'overlays', 'operations', 'alpha', 'SKILL.md');
  const operationText = '# Alpha operation\n\nUse [alpha](../../skills/alpha/SKILL.md), [beta](../../skills/beta/SKILL.md), and [routing](../../docs/agents/routing.md).\n';
  await writeFile(operationPath, operationText);
  await writeFile(join(repoRoot, 'overlays', 'schemas', 'alpha.json'), '{}\n');
  await writeFile(configPath, `${JSON.stringify({
    version: 2,
    personalSkills: ['alpha', 'beta'],
    repositorySkills: [],
    sharedDocs: ['routing.md'],
    sharedEvals: ['coding-skill-evals.json'],
    profiles: { reviewer_fast: 'reviewer-fast.toml' },
    overlayRoot: 'overlays',
    adaptations: [
      { id: 'resolved-codex-home', from: '<resolved-codex-home>', to: '$CODEX_ORCHESTRATOR_WORKFLOW_ROOT' },
      { id: 'default-codex-skills', from: '${CODEX_HOME:-$HOME/.codex}/skills', to: '../../skills' },
      { id: 'codex-home-skills', from: '$CODEX_HOME/skills', to: '../../skills' },
      { id: 'default-codex-docs', from: '${CODEX_HOME:-$HOME/.codex}/docs/agents/', to: '../../docs/agents/' },
      { id: 'codex-home-docs', from: '$CODEX_HOME/docs/agents/', to: '../../docs/agents/' },
    ],
    operations: {
      alpha: {
        entry: 'operations/alpha/SKILL.md', sourceSkill: 'alpha', dependencySkills: ['beta'],
        resources: ['docs/agents/routing.md'], outputSchema: 'schemas/alpha.json', profile: 'reviewer_fast',
        policy: {
          sandboxMode: 'read-only', cwdClass: 'worktree', worktreeAccess: 'read-only', writableRootClasses: [],
          runnerPostcondition: 'report-only', network: 'deny', networkHosts: [], mcpTools: [],
          approvalCeiling: 'never', externalWrite: false,
        },
      },
    },
  }, null, 2)}\n`);

  await execFileAsync(process.execPath, [script, 'sync', '--codex-home', codexHome, '--repo-root', repoRoot,
    '--config', configPath, '--output-root', outputRoot]);
  const manifest = JSON.parse(await readFile(join(outputRoot, 'manifest.json'), 'utf8')) as Record<string, any>;
  assert.equal(manifest.version, 2);
  assert.deepEqual(manifest.operations.alpha.dependencySkills, ['beta']);
  assert.equal(manifest.operations.alpha.files.includes('skills/beta/SKILL.md'), true);
  assert.equal(manifest.operations.alpha.files.includes('docs/agents/routing.md'), true);
  assert.equal(manifest.operations.alpha.files.some((path: string) => path.includes('/evals/')), false);
  assert.deepEqual(Object.values(manifest.evals).map((entry: any) => entry.path).sort(), [
    'evals/coding-skill-evals.json',
    'skills/alpha/evals/evals.json',
    'skills/beta/evals/evals.json',
  ]);

  const generatedOperationPath = join(outputRoot, 'operations', 'alpha', 'SKILL.md');
  const unlinkedOperation = Buffer.from('# Alpha operation\n\nUse [alpha](../../skills/alpha/SKILL.md), beta, and [routing](../../docs/agents/routing.md).\n');
  await writeFile(generatedOperationPath, unlinkedOperation);
  rehashV2File(manifest, 'operations/alpha/SKILL.md', unlinkedOperation);
  await writeFile(join(outputRoot, 'manifest.json'), `${canonicalJson(manifest)}\n`);
  await assert.rejects(execFileAsync(process.execPath, [script, 'verify', '--output-root', outputRoot]), /does not reference.*beta/iu);
  await execFileAsync(process.execPath, [script, 'sync', '--codex-home', codexHome, '--repo-root', repoRoot,
    '--config', configPath, '--output-root', outputRoot]);

  await writeFile(operationPath, '# Alpha operation\n\nUse [alpha](../../skills/alpha/SKILL.md) and [routing](../../docs/agents/routing.md).\n');
  await assert.rejects(execFileAsync(process.execPath, [script, 'sync', '--codex-home', codexHome, '--repo-root', repoRoot,
    '--config', configPath, '--output-root', outputRoot]), /does not reference.*beta/iu);
  await writeFile(operationPath, operationText);

  await writeFile(join(codexHome, 'skills', 'beta', 'evals', 'evals.json'), `${JSON.stringify({
    schema_version: 1,
    skill: 'beta',
    cases: [{ id: 'alpha-case', prompt: 'Duplicate.', expected: ['duplicate'], forbidden: ['unique'] }],
  })}\n`);
  await assert.rejects(execFileAsync(process.execPath, [script, 'sync', '--codex-home', codexHome, '--repo-root', repoRoot,
    '--config', configPath, '--output-root', outputRoot]), /eval case is invalid/iu);
});

test('workflow sync rejects config replacement after the initial authority read', async () => {
  const root = await mkdtemp(join(tmpdir(), 'workflow-import-config-race-'));
  const codexHome = join(root, 'codex-home');
  const repoRoot = join(root, 'repo');
  const outputRoot = join(root, 'output');
  const configPath = join(repoRoot, 'source.json');
  const replacementPath = join(repoRoot, 'replacement.json');
  const markerPath = join(root, 'config-read');
  const releasePath = join(root, 'release');
  await mkdir(join(codexHome, 'skills', 'alpha', 'agents'), { recursive: true });
  await mkdir(join(codexHome, 'docs', 'agents'), { recursive: true });
  await mkdir(join(codexHome, 'agents'), { recursive: true });
  await mkdir(join(repoRoot, 'overlays', 'operations', 'alpha'), { recursive: true });
  await mkdir(join(repoRoot, 'overlays', 'schemas'), { recursive: true });
  await writeFile(join(codexHome, 'skills', 'alpha', 'SKILL.md'), '# Alpha\n');
  await writeFile(join(codexHome, 'skills', 'alpha', 'agents', 'openai.yaml'), 'interface:\n  display_name: Alpha\n');
  await writeFile(join(codexHome, 'agents', 'reviewer-fast.toml'), 'name = "reviewer_fast"\nsandbox_mode = "read-only"\n');
  await writeFile(join(repoRoot, 'overlays', 'operations', 'alpha', 'SKILL.md'), '# Alpha operation\n');
  await writeFile(join(repoRoot, 'overlays', 'schemas', 'alpha.json'), '{}\n');
  const config = {
    version: 1,
    personalSkills: ['alpha'],
    repositorySkills: [],
    sharedDocs: [],
    profiles: { reviewer_fast: 'reviewer-fast.toml' },
    overlayRoot: 'overlays',
    adaptations: [
      { id: 'resolved-codex-home', from: '<resolved-codex-home>', to: '$CODEX_ORCHESTRATOR_WORKFLOW_ROOT' },
      { id: 'default-codex-skills', from: '${CODEX_HOME:-$HOME/.codex}/skills', to: '../../skills' },
      { id: 'codex-home-skills', from: '$CODEX_HOME/skills', to: '../../skills' },
      { id: 'default-codex-docs', from: '${CODEX_HOME:-$HOME/.codex}/docs/agents/', to: '../../docs/agents/' },
      { id: 'codex-home-docs', from: '$CODEX_HOME/docs/agents/', to: '../../docs/agents/' },
    ],
    operations: {
      alpha: {
        entry: 'operations/alpha/SKILL.md', sourceSkill: 'alpha', outputSchema: 'schemas/alpha.json',
        profile: 'reviewer_fast',
        policy: {
          sandboxMode: 'read-only', cwdClass: 'worktree', worktreeAccess: 'read-only', writableRootClasses: [],
          runnerPostcondition: 'report-only', network: 'deny', networkHosts: [], mcpTools: [],
          approvalCeiling: 'never', externalWrite: false,
        },
      },
    },
  };
  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`);
  await writeFile(replacementPath, `${JSON.stringify({ ...config, personalSkills: [] }, null, 2)}\n`);

  const sync = execFileAsync(process.execPath, [script, 'sync',
    '--codex-home', codexHome, '--repo-root', repoRoot, '--config', configPath, '--output-root', outputRoot], {
    env: {
      ...process.env,
      CODEX_ORCHESTRATOR_TEST_CONFIG_READ_MARKER: markerPath,
      CODEX_ORCHESTRATOR_TEST_CONFIG_READ_RELEASE: releasePath,
    },
  });
  await waitForPath(markerPath);
  await rename(replacementPath, configPath);
  await writeFile(releasePath, 'continue\n');

  await assert.rejects(sync, /Source changed during workflow import.*source\.json/iu);
  await assert.rejects(lstat(outputRoot), { code: 'ENOENT' });
});

async function waitForPath(path: string): Promise<void> {
  for (let attempt = 0; attempt < 1_000; attempt += 1) {
    try {
      await lstat(path);
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
      await new Promise((resolve) => setTimeout(resolve, 5));
    }
  }
  throw new Error(`Timed out waiting for ${path}`);
}

async function digestTree(root: string): Promise<Array<[string, number, string]>> {
  const rows: Array<[string, number, string]> = [];
  const visit = async (directory: string, relative = ''): Promise<void> => {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      const name = relative ? `${relative}/${entry.name}` : entry.name;
      if (entry.isDirectory()) await visit(path, name);
      else rows.push([name, (await stat(path)).mode & 0o777, await readFile(path, 'hex')]);
    }
  };
  await visit(root);
  return rows.sort((left, right) => left[0].localeCompare(right[0]));
}

function rehashV2File(manifest: Record<string, any>, path: string, bytes: Buffer): void {
  const file = manifest.files.find((entry: Record<string, unknown>) => entry.path === path);
  if (!file) throw new Error(`Missing fixture manifest file: ${path}`);
  file.size = bytes.length;
  file.sha256 = createHash('sha256').update(bytes).digest('hex');
  manifest.sourceFingerprint = createHash('sha256')
    .update(Buffer.from(`codex-orchestrator-workflow-source-v2\0${canonicalJson({ files: manifest.files })}`)).digest('hex');
  manifest.generationHash = '';
  manifest.generationHash = createHash('sha256')
    .update(Buffer.from(`codex-orchestrator-workflow-generation-v2\0${canonicalJson(manifest)}`)).digest('hex');
}

function canonicalJson(value: unknown): string {
  if (value === null || ['boolean', 'string', 'number'].includes(typeof value)) return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`;
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record).sort((left, right) => Buffer.compare(Buffer.from(left), Buffer.from(right)))
      .map((key) => `${JSON.stringify(key)}:${canonicalJson(record[key])}`).join(',')}}`;
  }
  throw new Error('unsupported fixture value');
}
